[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200  

[build]
  base = "client/"
  publish = "client/.next/"
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-nextjs"
