[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200  

[build]
  command = "npm run build"
  publish = "build/"

[plugins]
  package = '@netlify/plugin-nextjs'
  [plugins.inputs]
    disable = true
